server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/krekerok_tracker_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: update
